In [1]:
import pandas as pd

# Carico i 2 dataset
festival = pd.read_excel('~/EPICODE/Progetto Finale Looker/drive-download-20250804T194039Z-1-001/dati-festival-sanremo-1951-2023.xlsx')

classifica = pd.read_excel('~/EPICODE/Progetto Finale Looker/drive-download-20250804T194039Z-1-001/Ufficiale/dati-classifica-sanremo-1951-2023.xlsx')

display(festival.head(), classifica.head())

,Anno,Periodo,Sede,Presentatore,Partecipanti,Vincitore
0,1951,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,3,Nilla Pizzi
1,1952,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,5,Nilla Pizzi
2,1953,29-31 gennaio,Casinò di Sanremo,Nunzio Filogamo,10,Carla Boni
3,1954,28-30 gennaio,Casinò di Sanremo,Nunzio Filogamo,12,Gino Latilla
4,1955,27-29 gennaio,Casinò di Sanremo,Armando Pizzo,15,Claudio Villa

,Unnamed: 0,Posizione,Interprete,Canzone,anno,Autori
0,0,1º,Nilla Pizzi,Grazie dei fiori,1951,Gian Carlo Testoni e Mario Panzeri
1,1,2º,Nilla Pizzi e Achille Togliani,La luna si veste d'argento,1951,Biri
2,2,3º,Achille Togliani,Serenata a nessuno,1951,Walter Colì
3,3,F,Achille Togliani e Duo Fasano,Al mercato di Pizzighettone,1951,Aldo Locatelli
4,4,F,Nilla Pizzi e Achille Togliani,Eco tra gli abeti,1951,Enzo Bonagura

In [2]:
print(f'FESTIVAL: {festival.shape}')
print(f'CLASSIFICA: {classifica.shape}')

print('\nCOLONNE FESTIVAL:\n', list(festival.columns))
print('\nCOLONNE CLASSIFICA:\n', list(classifica.columns))

print(F'\nFESTIVAL INFO: \n{festival.info}\nCLASSIFICA INFO: \n{classifica.info}')

FESTIVAL: (73, 6)
CLASSIFICA: (1663, 6)

COLONNE FESTIVAL:
 ['Anno', 'Periodo', 'Sede', 'Presentatore', 'Partecipanti', 'Vincitore']

COLONNE CLASSIFICA:
 ['Unnamed: 0', 'Posizione', 'Interprete', 'Canzone', 'anno', 'Autori']

FESTIVAL INFO:
<bound method DataFrame.info of     Anno         Periodo               Sede                     Presentatore  \
0   1951   29-31 gennaio  Casinò di Sanremo                  Nunzio Filogamo
1   1952   28-30 gennaio  Casinò di Sanremo                  Nunzio Filogamo
2   1953   29-31 gennaio  Casinò di Sanremo                  Nunzio Filogamo
3   1954   28-30 gennaio  Casinò di Sanremo                  Nunzio Filogamo
4   1955   27-29 gennaio  Casinò di Sanremo                    Armando Pizzo
..   ...             ...                ...                              ...
68  2019  5 - 9 febbraio     Teatro Ariston                 Claudio Baglioni
69  2020  4 - 8 febbraio     Teatro Ariston  Amadeus (conduttore televisivo)
70  2021     2 - 6 marzo     Teatro Ariston  Amadeus (conduttore televisivo)
71  2022   1º-5 febbraio     Teatro Ariston  Amadeus (conduttore televisivo)
72  2023   7-11 febbraio     Teatro Ariston  Amadeus (conduttore televisivo)

    Partecipanti           Vincitore
0              3         Nilla Pizzi
1              5         Nilla Pizzi
2             10          Carla Boni
3             12        Gino Latilla
4             15       Claudio Villa
..           ...                 ...
68            24             Mahmood
69            32  Diodato (cantante)
70            34            Måneskin
71            25             Mahmood
72            28       Marco Mengoni

[73 rows x 6 columns]>
CLASSIFICA INFO:
<bound method DataFrame.info of       Unnamed: 0 Posizione                      Interprete  \
0              0        1º                     Nilla Pizzi
1              1        2º  Nilla Pizzi e Achille Togliani
2              2        3º                Achille Togliani
3              3         F   Achille Togliani e Duo Fasano
4              4         F  Nilla Pizzi e Achille Togliani
...          ...       ...                             ...
1658        1659       24º                            Olly
1659        1660       25º                        Anna Oxa
1660        1661       26º                            Will
1661        1662       27º                           Shari
1662        1663       28º                           Sethu

                          Canzone  anno  \
0                Grazie dei fiori  1951
1      La luna si veste d'argento  1951
2              Serenata a nessuno  1951
3     Al mercato di Pizzighettone  1951
4               Eco tra gli abeti  1951
...                           ...   ...
1658                      Polvere  2023
1659      Sali (canto dell'anima)  2023
1660                      Stupido  2023
1661                      Egoista  2023
1662                  Cause perse  2023

                                         Autori
0            Gian Carlo Testoni e Mario Panzeri
1                                          Biri
2                                   Walter Colì
3                                Aldo Locatelli
4                                 Enzo Bonagura
...                                         ...
1658               Olly, E. Lovito e J. Boverod
1659  A. Oxa, F. Bianconi, Kaballà e F. Zanotti
1660           Will, S. Cremonini e A. Pugliese
1661  Shari, M. Pisciottu, L. Fenudi e R. Puddu
1662                  M. De Lauri e G. De Lauri

[1663 rows x 6 columns]>

In [3]:
#Modifico in minuscolo i nomi di tutte le colonne per comodità
festival.columns = festival.columns.str.strip().str.lower()
classifica.columns = classifica.columns.str.strip().str.lower()

***

### ANALISI E MODIFICHE TABELLA 'CLASSIFICA'

In [4]:
#controllo se ci sono duplicati
print('Duplicati in classifica:', classifica.duplicated().sum())

#controllo se ci sono nulli
print('\n','Classifica: \n', classifica.isnull().sum())

Duplicati in classifica: 0

 Classifica:
 unnamed: 0     0
posizione     10
interprete     0
canzone        0
anno           0
autori         0
dtype: int64

In [5]:
#Controllo i valori nulli all'interno della colonna "Posizione"
classifica.loc[classifica["posizione"].isna()]

,unnamed: 0,posizione,interprete,canzone,anno,autori
1309,1310,NaN,Amalia Gré,Amami per sempre,2007,"A. Grezio, M. Ranauro e P. Palma"
1310,1311,NaN,Marcella e Gianni Bella,Forever per sempre,2007,Mogol e G. Bella
1311,1312,NaN,Stadio,Guardami,2007,S. Grandi e G. Curreri
1312,1313,NaN,Paolo Rossi,In Italia si sta male (si sta bene anziché no),2007,R. Gaetano
1313,1314,NaN,Nada,Luna in piena,2007,N. Malanima
1314,1315,NaN,Johnny Dorelli,Meglio così,2007,G. Calabrese e G. Ferrio
1315,1316,NaN,Fabio Concato,Oltre il giardino,2007,F. Concato
1316,1317,NaN,Leda Battisti,Senza me ti pentirai,2007,L. Battisti e A. Battaglia
1317,1318,NaN,Milva,The Show Must Go On,2007,G. Faletti
1318,1319,NaN,Velvet,Tutto da rifare,2007,"A. Sgreccia, G. Cornetta, P. Ferrantini e P. B..."

In [6]:
#SOSTITUISCO TUTTI I VALORI NULL 

#Trovo i NaN nella colonna Posizione
mask = classifica["posizione"].isna()

#Conto quanti NaN ci sono
n_nan = mask.sum()

#Creo la sequenza che parte da 11 e lunga quanto i NaN
nuovi_valori = range(11, 11 + n_nan)

#Sostituisco i NaN con i nuovi valori
classifica.loc[mask, "posizione"] = nuovi_valori

In [7]:
#Elimino la colonna Unnamed: 0
classifica.drop(columns=['unnamed: 0'], inplace=True)

In [8]:
#Cambio il formato della colonna anno da int a datetime
classifica['anno'] = pd.to_datetime(classifica['anno'].astype(str), format='%Y')
festival['anno'] = pd.to_datetime(festival['anno'].astype(str), format='%Y')

In [24]:
#Elimino i record dove ci sono i valori F/NF in quanto non sono classificabili e non utili ai fini del report
classifica.drop(classifica[classifica['posizione'].isin(['F', 'NF'])].index, inplace=True)

#Tengo solo le cifre dalla colonna 'posizione'
solo_cifre = (classifica['posizione']
       .astype('string')
       .str.replace(r'[^0-9]', '', regex=True)   # elimina tutto ciò che non è una cifra
       .str.strip())

#Converto a int
classifica["posizione"] = pd.to_numeric(solo_cifre, errors="coerce").astype("Int64")

print(classifica['posizione'].dtype)  
classifica.head(5)

Int64

,posizione,interprete,canzone,anno,autori,interprete_lista,interprete_1,interprete_2,interprete_3,interprete_4,...,autori_lista,autori_1,autori_2,autori_3,autori_4,autori_5,autori_6,autori_7,autori_8,autori_9
0,1,Nilla Pizzi,Grazie dei fiori,1951-01-01,"Gian Carlo Testoni , Mario Panzeri",[Nilla Pizzi],Nilla Pizzi,None,None,None,...,"[Gian Carlo Testoni , Mario Panzeri]",Gian Carlo Testoni,Mario Panzeri,None,None,None,None,None,None,None
1,2,"Nilla Pizzi , Achille Togliani",La luna si veste d'argento,1951-01-01,Biri,"[Nilla Pizzi , Achille Togliani]",Nilla Pizzi,Achille Togliani,None,None,...,[Biri],Biri,None,None,None,None,None,None,None,None
2,3,Achille Togliani,Serenata a nessuno,1951-01-01,Walter Colì,[Achille Togliani],Achille Togliani,None,None,None,...,[Walter Colì],Walter Colì,None,None,None,None,None,None,None,None
20,1,Nilla Pizzi,Vola Colomba,1952-01-01,"B. Cherubini , C. Concina",[Nilla Pizzi],Nilla Pizzi,None,None,None,...,"[B. Cherubini , C. Concina]",B. Cherubini,C. Concina,None,None,None,None,None,None,None
21,2,Nilla Pizzi,Papaveri e papere,1952-01-01,"N. Rastelli, M. Panzeri , V. Mascheroni",[Nilla Pizzi],Nilla Pizzi,None,None,None,...,"[N. Rastelli, M. Panzeri , V. Mascheroni]",N. Rastelli,M. Panzeri,V. Mascheroni,None,None,None,None,None,None

In [10]:
#Sostituisco tutti i connettori nella colonna 'interprete' con una ',' per semplificare l'estrazione dei vari nomi

#Creo un dizionario per sostituiri i vari connettori con una ',' 
sostituzioni = {
    r'(?i)\be\b' : ',',
    r'(?i)\bed\b' : ',',
    r'(?i)\bcon\b' : ',',
    r'(?i)\bfeat\.?\b' : ',',
    r'(?i)\bfeaturing\b' : ',',
    r'&' : ',',
    r'/' : ',',
    r'-' : ','
}

#Sostituisco i connettori
classifica['interprete'] = classifica['interprete'].replace(sostituzioni, regex=True).str.strip()

#Creo una lista che mi servirà dopo
classifica['interprete_lista'] = classifica['interprete'].str.split(',')

#Creo x colonne per x interpreti
classifica[[
    'interprete_1', 
    'interprete_2', 
    'interprete_3', 
    'interprete_4',
    'interprete_5'
]] = pd.DataFrame(classifica['interprete_lista'].to_list(), index=classifica.index)

In [11]:
#replico lo stesso per "autore"

classifica['autori'] = classifica['autori'].replace(sostituzioni, regex=True).str.strip()

classifica['autori_lista'] = classifica['autori'].str.split(',')

classifica[[
    'autori_1', 
    'autori_2', 
    'autori_3', 
    'autori_4',
    'autori_5', 
    'autori_6', 
    'autori_7', 
    'autori_8', 
    'autori_9'
]] = pd.DataFrame(classifica['autori_lista'].to_list(), index=classifica.index)

In [12]:
classifica.sample(5)

,posizione,interprete,canzone,anno,autori,interprete_lista,interprete_1,interprete_2,interprete_3,interprete_4,...,autori_lista,autori_1,autori_2,autori_3,autori_4,autori_5,autori_6,autori_7,autori_8,autori_9
1438,13,Ron,Sing in the rain,2014-01-01,"Ron, M. Del Forno",[Ron],Ron,None,None,None,...,"[Ron, M. Del Forno]",Ron,M. Del Forno,None,None,None,None,None,None,None
60,1,"Giorgio Consolini , Gino Latilla",Tutte le mamme,1954-01-01,"U. Bertini , ,. Falcocchio","[Giorgio Consolini , Gino Latilla]",Giorgio Consolini,Gino Latilla,None,None,...,"[U. Bertini , , . Falcocchio]",U. Bertini,,. Falcocchio,None,None,None,None,None,None
510,10,Anna Identici,Mi son chiesta tante volte,1973-01-01,"P. P. Preti , G. Guarneri",[Anna Identici],Anna Identici,None,None,None,...,"[P. P. Preti , G. Guarneri]",P. P. Preti,G. Guarneri,None,None,None,None,None,None,None
654,10,Pandemonium,Tu fai schifo sempre,1979-01-01,"A. Giordano, M. Paulicelli , G. Mauro",[Pandemonium],Pandemonium,None,None,None,...,"[A. Giordano, M. Paulicelli , G. Mauro]",A. Giordano,M. Paulicelli,G. Mauro,None,None,None,None,None,None
795,5,Fiordaliso,Non voglio mica la luna,1984-01-01,",. Malepasso, L. Albertelli , A. Fornaciari",[Fiordaliso],Fiordaliso,None,None,None,...,"[, . Malepasso, L. Albertelli , A. Fornaciari]",,. Malepasso,L. Albertelli,A. Fornaciari,None,None,None,None,None

***

### ANALISI E MODIFICHE TABELLA 'FESTIVAL'

In [13]:
#controllo se ci sono duplicati
print('Duplicati in festival:', festival.duplicated().sum())

#controllo se ci sono nulli
print('\n','Festival: \n', festival.isnull().sum())

Duplicati in festival: 0

 Festival:
 anno            0
periodo         0
sede            0
presentatore    0
partecipanti    0
vincitore       0
dtype: int64

In [14]:
#Elimino tutti i valori nelle parentesi nella colonna 'presentatore'
festival['presentatore'] = festival['presentatore'].str.split('(', n=1).str[0].str.strip()

In [15]:
festival.sample(15)

,anno,periodo,sede,presentatore,partecipanti,vincitore
12,1963-01-01,7-9 febbraio,Casinò di Sanremo,Mike Bongiorno,21,Tony Renis
70,2021-01-01,2 - 6 marzo,Teatro Ariston,Amadeus,34,Måneskin
24,1975-01-01,27 febbraio - 1º marzo 1975,Casinò di Sanremo,Mike Bongiorno,30,Gilda (cantante)
72,2023-01-01,7-11 febbraio,Teatro Ariston,Amadeus,28,Marco Mengoni
13,1964-01-01,30 gennaio - 1º febbraio 1964,Casinò di Sanremo,Mike Bongiorno,40,Gigliola Cinquetti
64,2015-01-01,10 - 14 febbraio,Teatro Ariston,Carlo Conti,28,Il Volo (gruppo musicale anni 2010)
25,1976-01-01,19 ‒ 21 febbraio 1976,Casinò di Sanremo,Giancarlo Guardabassi,30,Peppino di Capri
9,1960-01-01,28-30 gennaio,Casinò di Sanremo,Paolo Ferrari,23,Tony Dallara
69,2020-01-01,4 - 8 febbraio,Teatro Ariston,Amadeus,32,Diodato (cantante)
23,1974-01-01,7-9 marzo,Casinò di Sanremo,Corrado,28,Iva Zanicchi
10,1961-01-01,26 gennaio - 6 febbraio,Casinò di Sanremo,Lilli Lembo,42,Betty Curtis
14,1965-01-01,28-30 gennaio,Casinò di Sanremo,Mike Bongiorno,43,Bobby Solo
27,1978-01-01,26-28 gennaio,Teatro Ariston,Maria Giovanna Elmi,14,Matia Bazar
43,1994-01-01,23 - 26 febbraio,Teatro Ariston,Pippo Baudo,38,Aleandro Baldi
36,1987-01-01,4 - 7 febbraio,Teatro Ariston,Pippo Baudo,40,Gianni Morandi

***

## SCARICO I FILE LAVORATI

In [16]:
#scarico i file lavorati
classifica.to_csv("CLASSIFICA.csv", index=False)
festival.to_csv("PRESENTATORI.csv", index=False)

#file solo autori
autori_exploded = classifica.explode("autori_lista").copy()
autori_exploded.rename(columns={"autori_lista": "autore"}, inplace=True)
#seleziono solo le colonne che mi serviranno
autori_light = autori_exploded[["anno", "canzone", "posizione", "autore"]]
autori_light.to_csv("AUTORI.csv", index=False)

#file solo interpreti
interpreti_exploded = classifica.explode("interprete_lista").copy()
interpreti_exploded.rename(columns={"interprete_lista": "interprete"}, inplace=True)
#seleziono solo le colonne che mi serviranno
interpreti_light = interpreti_exploded[["anno", "canzone", "posizione", "interprete"]]
interpreti_light.to_csv("INTERPRETI.csv", index=False)