Esercizio 1: Esaminiamo il dataset: • quanti dati ci sono in totale? • quali sono i metadati? • stampiamo il primo elemento • stampiamo l'ultimo elemento • riusciamo a stampare un elemento a caso? • quali sono gli anni di inserimento presenti? • quante attività ci sono nel quadrato di longitudine 9-10 e latitudine 45-46? • quante attività ci sono nella provincia di Vicenza? • quante enoteche ci sono, e come si chiamano? 3 • quante attività ci sono in Lazio e Abruzzo assieme?

In [1]:
import pandas as pd
mappa_df = pd.read_csv("~/Downloads/Mappa-dei-pub-circoli-locali-in-Italia.csv", encoding="latin1", sep=";")

In [2]:
# 1. Quanti dati ci sono in totale?
mappa_df.shape

(2635, 9)

In [3]:
# 2. Quali sono i metadati?
mappa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2635 entries, 0 to 2634
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Comune                           2635 non-null   object
 1   Provincia                        2635 non-null   object
 2   Regione                          2635 non-null   object
 3   Nome                             2337 non-null   object
 4   Anno inserimento                 2635 non-null   int64
 5   Data e ora inserimento           2635 non-null   object
 6   Identificatore in OpenStreetMap  2635 non-null   int64
 7   Longitudine                      2635 non-null   float64
 8   Latitudine                       2635 non-null   float64
dtypes: float64(2), int64(2), object(5)
memory usage: 185.4+ KB

In [4]:
# 3. Primo elemento
mappa_df.head(1)

,Comune,Provincia,Regione,Nome,Anno inserimento,Data e ora inserimento,Identificatore in OpenStreetMap,Longitudine,Latitudine
0,ALTRO,ALTRO,ALTRO,NaN,2011,2011-06-25T23:17:43Z,1339088150,13.733257,45.57583

In [5]:
# 4. Ultimo elemento
mappa_df.tail(1)

,Comune,Provincia,Regione,Nome,Anno inserimento,Data e ora inserimento,Identificatore in OpenStreetMap,Longitudine,Latitudine
2634,TRANI,BARLETTA-ANDRIA-TRANI,Puglia,Well's Fargo,2009,2009-08-10T12:44:03Z,387223648,16.436765,41.267264

In [6]:
# 5. Un elemento a caso
mappa_df.sample(1)

,Comune,Provincia,Regione,Nome,Anno inserimento,Data e ora inserimento,Identificatore in OpenStreetMap,Longitudine,Latitudine
2424,SASSARI,SASSARI,Sardegna,BNO,2014,2014-08-09T06:18:33Z,3006194733,8.561194,40.727961

In [7]:
# 6. Anni di inserimento presenti
mappa_df["Anno inserimento"].sort_values(ascending=False).unique()

array([2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007])

In [8]:
mappa_df

,Comune,Provincia,Regione,Nome,Anno inserimento,Data e ora inserimento,Identificatore in OpenStreetMap,Longitudine,Latitudine
0,ALTRO,ALTRO,ALTRO,NaN,2011,2011-06-25T23:17:43Z,1339088150,13.733257,45.575830
1,ALTRO,ALTRO,ALTRO,Lenny's Pub,2011,2011-07-29T17:22:56Z,1375887295,12.418681,46.747584
2,ALTRO,ALTRO,ALTRO,Murrayfield Pub,2015,2015-10-24T09:28:06Z,3323888102,9.029585,45.831340
3,ALTRO,ALTRO,ALTRO,Snop?e,2010,2010-09-22T08:32:52Z,921157802,13.640939,45.954607
4,ALA DI STURA,CITTA' METROPOLITANA DI TORINO,Piemonte,NaN,2012,2012-05-21T14:28:45Z,1760949034,7.307306,45.313150
...,...,...,...,...,...,...,...,...,...
2630,BARLETTA,BARLETTA-ANDRIA-TRANI,Puglia,Santa Croce,2010,2010-01-17T16:15:08Z,615632993,16.285782,41.320671
2631,BISCEGLIE,BARLETTA-ANDRIA-TRANI,Puglia,Auld Dublin,2014,2014-03-03T20:56:16Z,2613737619,16.497204,41.241814
2632,BISCEGLIE,BARLETTA-ANDRIA-TRANI,Puglia,Ferus,2014,2014-01-07T19:22:18Z,2613737620,16.506175,41.240957
2633,TRANI,BARLETTA-ANDRIA-TRANI,Puglia,Re Artù,2009,2009-09-04T07:57:05Z,482836935,16.418124,41.281518
2634,TRANI,BARLETTA-ANDRIA-TRANI,Puglia,Well's Fargo,2009,2009-08-10T12:44:03Z,387223648,16.436765,41.267264

In [9]:
# 7. Attività nel quadrato longitudine 9-10, latitudine 45-46
len(
    mappa_df.loc[
        (mappa_df["Longitudine"] >= 9) & (mappa_df["Longitudine"] <= 10) &
        (mappa_df["Latitudine"] >= 45) & (mappa_df["Latitudine"] <= 46)
])

306

In [10]:
# 8. Attività nella provincia di Vicenza
len(mappa_df[mappa_df["Provincia"] == "VICENZA"])

73

In [11]:
# 9. Enoteche: quante e come si chiamano
enoteche = mappa_df[mappa_df["Nome"].str.contains("enoteca", case = False, na = False)]
print("Numero enoteche: ", len(enoteche))
print("Nomi enoteche:\n", enoteche["Nome"])

Numero enoteche:  6
Nomi enoteche:
 64      Enoteca con Cucina""Tirolin""
496                 Concordia Enoteca
1003                  Enoteca Umberto
1491          Enoteca ""Al Brindisi""
1492           Enoteca ""da Massimo""
1723         Enoteca Il Violino Rosso
Name: Nome, dtype: object

In [12]:
# 10. Attività in Lazio e Abruzzo
len(
    mappa_df.loc[
        (mappa_df["Regione"] == "Lazio") |
        (mappa_df["Regione"] == "Abruzzo")
    ])

337

Esercizio 2: Il dataset insurance.csv dei beginner_datasets contiene dati su caratteristiche e abitudini delle persone rispetto ai costi individuali per le cure mediche come premio per le assicurazioni sulla salute. • Visualizziamone le dimensioni, un'anteprima, e osserviamo i nomi di colonna; • Quali sono le medie di charges rispetto a region? Ci sono differenze significative? • E rispetto a smoker? E a sex? • Quali sono i descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi? Nota: è lo stesso esercizio della volta scorsa, ma stavolta da eseguire con il metodo .groupby()

In [13]:
insurance_df = pd.read_csv("~/Desktop/Python - Epicode/datasets/beginner_datasets/insurance.csv")

In [14]:
# 1. Dimensioni del dataset
print("Dimensioni:", insurance_df.shape)

Dimensioni: (1338, 7)

In [15]:
# 2. Anteprima
print("\nPrime righe:")
print(insurance_df.head())

Prime righe:
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
# 3. Nomi delle colonne
print("\nColonne:")
print(insurance_df.columns)

Colonne:
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [17]:
insurance_df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [19]:
insurance_df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [20]:
# 4. Media di charges rispetto a region?
insurance_df.groupby("region")["charges"].mean().round(2)

region
northeast    13406.38
northwest    12417.58
southeast    14735.41
southwest    12346.94
Name: charges, dtype: float64

In [21]:
# 5. Media di charges rispetto a smoker
insurance_df.groupby("smoker")["charges"].mean().round(2)

smoker
no      8434.27
yes    32050.23
Name: charges, dtype: float64

In [22]:
# 6. Media di charges rispetto a sex
insurance_df.groupby("sex")["charges"].mean().round(2)

sex
female    12569.58
male      13956.75
Name: charges, dtype: float64

La differenza sostanziale la vediamo nella categoria smoker

In [23]:
# 7. Descrittori statistici di bmi? Quali sono minimo, media e massimo di charges rispetto ai diversi quartili dei valori di bmi? 
insurance_df.describe().round(2)

           age      bmi  children   charges
count  1338.00  1338.00   1338.00   1338.00
mean     39.21    30.66      1.09  13270.42
std      14.05     6.10      1.21  12110.01
min      18.00    15.96      0.00   1121.87
25%      27.00    26.30      0.00   4740.29
50%      39.00    30.40      1.00   9382.03
75%      51.00    34.69      2.00  16639.91
max      64.00    53.13      5.00  63770.43

In [25]:
# 8. Minimo rispetto di quartili di bmi
q1 = insurance_df[insurance_df["bmi"] <= 26.30]
q2 = insurance_df[(insurance_df["bmi"] > 26.30) & (insurance_df["bmi"] <= 30.40)]
q3 = insurance_df[(insurance_df["bmi"] > 30.40) & (insurance_df["bmi"] <= 34.69)]
q4 = insurance_df[insurance_df["bmi"] > 34.69]

print("Primo quartile: ", "Minimo: ", q1["charges"].min())
print("Secondo quartile: ", "Minimo: ", q2["charges"].min())
print("Terzo quartile: ", "Minimo: ", q3["charges"].min())
print("Quarto quartile: ", "Minimo: ", q4["charges"].min())

Primo quartile:  Minimo:  1121.8739
Secondo quartile:  Minimo:  1131.5066
Terzo quartile:  Minimo:  1135.9407
Quarto quartile:  Minimo:  1141.4451

In [26]:
# 9. Media di charges rispetto ai quartili di bmi
print("Primo quartile: ", "Media: ", q1["charges"].mean().round(2))
print("Secondo quartile: ", "Media: ", q2["charges"].mean().round(2))
print("Terzo quartile: ", "Media: ", q3["charges"].mean().round(2))
print("Quarto quartile: ", "Media: ", q4["charges"].mean().round(2))

Primo quartile:  Media:  10360.66
Secondo quartile:  Media:  11407.83
Terzo quartile:  Media:  14358.17
Quarto quartile:  Media:  16987.94

In [27]:
#10. Massimo di charges rispetto ai quartili di bmi
print("Primo quartile: ", "Massimo: ", q1["charges"].max())
print("Secondo quartile: ", "Massimo: ", q2["charges"].max())
print("Terzo quartile: ", "Massimo: ", q3["charges"].max())
print("Quarto quartile: ", "Massimo: ", q4["charges"].max())

Primo quartile:  Massimo:  38245.59327
Secondo quartile:  Massimo:  62592.87309
Terzo quartile:  Massimo:  60021.39897
Quarto quartile:  Massimo:  63770.42801

Esercizio 3: Carichiamo in un DataFrame il dataset iris.csv dei beginner_datasets e calcoliamo: • La media della lunghezza dei petali di tutto il dataset • La media della lunghezza dei petali per ogni specie di Iris, utilizzando il metodo .groupby() • Media, minimo e massimo della larghezza dei sepali per ogni specie, utilizzando .groupby() e .agg()

In [29]:
iris_df = pd.read_csv("~/Desktop/Python - Epicode/datasets/beginner_datasets/iris.csv")
iris_df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [31]:
# 1. Media della lunghezza dei petali di tutto il dataset
iris_df["petal_length"].mean().round(2)

3.76

In [32]:
# 2. Media della lunghezza dei petali per ogni specie di Iris
iris_df.groupby("species")["petal_length"].mean().round(2)

species
Iris-setosa        1.46
Iris-versicolor    4.26
Iris-virginica     5.55
Name: petal_length, dtype: float64

In [34]:
#Media, minimo e massimo della larghezza dei sepali per ogni specie, utilizzando .groupby() e .agg()
iris_df.groupby("species")["sepal_width"].agg(["mean", "min", "max"])

                  mean  min  max
species
Iris-setosa      3.418  2.3  4.4
Iris-versicolor  2.770  2.0  3.4
Iris-virginica   2.974  2.2  3.8

Esercizio 4: Nei beginner_datasets, il dataset wine.csv contiene delle analisi organolettiche su diverse qualità di vini: • Qual è la media di concentrazione alcolica per ogni qualità? Ci sono differenze? E rispetto alla media totale? • C'è differenza nella concentrazione alcolica per vini bianchi e vini rossi? • Rifacendo le analisi dei due punti precedenti ma per il pH, cambia qualcosa? • E per i solfati?

In [35]:
wine_df = pd.read_csv("~/Desktop/Python - Epicode/datasets/beginner_datasets/wine.csv")
wine_df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white
6493,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white
6494,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white
6495,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white
6496,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white

In [36]:
# 1. Media di concentrazione alcolica per ogni qualità + media totale
print("Media totale = ", wine_df["alcohol"].mean().round(2)) #media totale
print(wine_df.groupby("quality")["alcohol"].mean().round(2)) #media per qualità

print("Più aumenta la qualità e più la gradazione alcolica aumenta. Inoltre possiamo osservare che la media totale si attesta al livello 6 di qualità")

Media totale =  10.49
quality
3    10.22
4    10.18
5     9.84
6    10.59
7    11.39
8    11.68
9    12.18
Name: alcohol, dtype: float64
Più aumenta la qualità e più la gradazione alcolica aumenta. Inoltre possiamo osservare che la media totale si attesta al livello 6 di qualità

In [38]:
# 2. Concentrazione alcolica per vini bianchi e vini rossi
print(wine_df.groupby("type")["alcohol"].mean().round(2))
print("Tra vino bianco e rosso non c'è quasi alcuna differenza")

type
red      10.42
white    10.51
Name: alcohol, dtype: float64
Tra vino bianco e rosso non c'è quasi alcuna differenza

In [39]:
# 3. Rifaccio le analisi dei due punti precedenti ma per il pH 
print("Media totale = ", wine_df["pH"].mean().round(2)) #media totale
print(wine_df.groupby("quality")["pH"].mean().round(2)) #media per qualità

print(wine_df.groupby("type")["pH"].mean().round(2))

print("Per il pH possiamo vedere che i valori sono molto simili tra loro e di conseguenza alla media totale")

Media totale =  3.22
quality
3    3.26
4    3.23
5    3.21
6    3.22
7    3.23
8    3.22
9    3.31
Name: pH, dtype: float64
type
red      3.31
white    3.19
Name: pH, dtype: float64
Per il pH possiamo vedere che i valori sono molto simili tra loro e di conseguenza alla media totale

In [40]:
# 4. adesso per i solfati
print("Media totale = ", wine_df["sulphates"].mean().round(2)) #media totale
print(wine_df.groupby("quality")["sulphates"].mean().round(2)) #media per qualità

print(wine_df.groupby("type")["sulphates"].mean().round(2))

print("Per il pH possiamo vedere che i valori sono molto simili tra loro e di conseguenza alla media totale")

Media totale =  0.53
quality
3    0.51
4    0.51
5    0.53
6    0.53
7    0.55
8    0.51
9    0.47
Name: sulphates, dtype: float64
type
red      0.66
white    0.49
Name: sulphates, dtype: float64
Per il pH possiamo vedere che i valori sono molto simili tra loro e di conseguenza alla media totale

Esercizio 5 Nei beginner_datasets, il file boston.csv contiene il Boston Housing Dataset, che deriva dalle informazioni raccolte dal Census Service degli Stati Uniti sulle abitazioni nell'area di Boston. Di seguito vengono descritte le colonne del dataset: • CRIM -tasso di criminalità pro capite per città • ZN - proporzione di terreni residenziali suddivisi in zone per lotti superiori a 25.000 piedi quadrati. • INDUS - percentuale di acri di attività commerciali non al dettaglio per città. • CHAS -variabile dummy del fiume Charles (1 se il tratto costeggia il fiume; 0 altrimenti)
• NOX -concentrazione di ossidi di azoto (parti per 10 milioni). • RM -numero medio di stanze per abitazione • AGE -proporzione di unità abitative occupate da proprietari costruite prima del 1940 • DIS - distanze ponderate da cinque centri occupazionali di Boston • RAD -indice di accessibilità alle autostrade radiali • TAX -aliquota dell'imposta fondiaria sul valore pieno per 10.000 dollari • PTRATIO - rapporto alunni-insegnanti per città • BLACK -la percentuale di neri per città • LSTAT - % di popolazione di condizione più bassa 8 • MEDV -Valore mediano delle case, espresso in migliaia di dollari
• La media del prezzo delle case cambia a seconda della distanza dal fiume Charles? • Si nota una correlazione tra il tasso di criminalità e il valore delle abitazioni? Come si può spiegare il risultato? • Qual è la media del numero di stanze rispetto al rapporto alunni-insegnanti? E del valore delle case? Appare esserci una qualche correlazione? Come si può spiegare il risultato? • Rispetto all'accessibilità alle autostrade, cambia qualcosa la media delle età delle abitazioni? E del numero di stanze? E delle tasse?

In [42]:
boston_df = pd.read_csv("~/Desktop/Python - Epicode/datasets/beginner_datasets/boston.csv")
boston_df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [43]:
#La media del prezzo delle case cambia a seconda della distanza dal fiume Charles?
print(boston_df.groupby("chas")["medv"].mean().round(2))

print("Come possiamo vedere le case vicino al fiume costano di più")

chas
0    22.09
1    28.44
Name: medv, dtype: float64
Come possiamo vedere le case vicino al fiume costano di più

In [44]:
#Si nota una correlazione tra il tasso di criminalità e il valore delle abitazioni? Come si può spiegare il risultato? 
boston_df["crim"].describe().round(2)
alto_tasso = boston_df["crim"] > 3.61
basso_tasso = boston_df["crim"] < 3.61

print("Prezzo medio con ALTO tasso di criminalità: ", boston_df[alto_tasso]["medv"].mean().round(2))
print("Prezzo medio con BASSO tasso di criminalità: ",boston_df[basso_tasso]["medv"].mean().round(2))

Prezzo medio con ALTO tasso di criminalità:  16.2
Prezzo medio con BASSO tasso di criminalità:  24.68

In [45]:
#Qual è la media del numero di stanze rispetto al rapporto alunni-insegnanti? E del valore delle case? Appare esserci una qualche correlazione? Come si può spiegare il risultato?
mediana_ptratio = boston_df["ptratio"].median()
print("Mediana ptratio:", mediana_ptratio)

alto_ptratio = boston_df["ptratio"] > mediana_ptratio  # Molti alunni per insegnante
basso_ptratio = boston_df["ptratio"] <= mediana_ptratio  # Pochi alunni per insegnante

print("Numero medio stanze con ALTO rapporto alunni-insegnanti:", boston_df[alto_ptratio]["rm"].mean().round(2)) # rapporto ptratio-numero stanze
print("Numero medio stanze con BASSO rapporto alunni-insegnanti:", boston_df[basso_ptratio]["rm"].mean().round(2)) # rapporto ptratio-numero stanze

print("Prezzo medio con ALTO rapporto alunni-insegnanti:", boston_df[alto_ptratio]["medv"].mean().round(2)) # rapporto medv-numero stanze
print("Prezzo medio con BASSO rapporto alunni-insegnanti:", boston_df[basso_ptratio]["medv"].mean().round(2)) # rapporto medv-numero stanze

print("--Possiamo vedere che il rapporto alunni-insegnati non influisce sul numero di stanze medio, ma il costo delle case influisce.")
print("Più il rapporto tra alunni e insegnanti è basso, più le case costano--")

Mediana ptratio: 19.05
Numero medio stanze con ALTO rapporto alunni-insegnanti: 6.06
Numero medio stanze con BASSO rapporto alunni-insegnanti: 6.51
Prezzo medio con ALTO rapporto alunni-insegnanti: 18.11
Prezzo medio con BASSO rapporto alunni-insegnanti: 26.96
--Possiamo vedere che il rapporto alunni-insegnati non influisce sul numero di stanze medio, ma il costo delle case influisce.
Più il rapporto tra alunni e insegnanti è basso, più le case costano--

In [46]:
#Rispetto all'accessibilità alle autostrade, cambia qualcosa la media delle età delle abitazioni? E del numero di stanze? E delle tasse?
mediana_rad = boston_df["rad"].median() #calcolo la mediana "rad"

alto_rad = boston_df["rad"] > mediana_rad #alto indice accessibilità autostrade
basso_rad = boston_df["rad"] <= mediana_rad #basso indice accessibilità autostrade

print("=== ALTA accessibilità autostrade ===")
print("Età media abitazioni:", boston_df[alto_rad]["age"].mean().round(2))
print("Numero medio stanze:", boston_df[alto_rad]["rm"].mean().round(2))  
print("Tasse medie:", boston_df[alto_rad]["tax"].mean().round(2))

print("\n=== BASSA accessibilità autostrade ===")
print("Età media abitazioni:", boston_df[basso_rad]["age"].mean().round(2))
print("Numero medio stanze:", boston_df[basso_rad]["rm"].mean().round(2))
print("Tasse medie:", boston_df[basso_rad]["tax"].mean().round(2))

print("\nPossiamo vedere come l'accessibilità all'autostrada influisce notevolmente sulle tasse medie e in percentuale più bassa sull'età delle abitazioni")

=== ALTA accessibilità autostrade ===
Età media abitazioni: 78.98
Numero medio stanze: 6.2
Tasse medie: 552.82

=== BASSA accessibilità autostrade ===
Età media abitazioni: 61.83
Numero medio stanze: 6.34
Tasse medie: 314.51

Possiamo vedere come l'accessibilità all'autostrada influisce notevolmente sulle tasse medie e in percentuale più bassa sull'età delle abitazioni

Esercizio 6: Abbiamo un DataFrame di dipendenti: employees_df = pd.DataFrame({ 'employee_id': [101, 102, 103, 104, 105], 'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma'], 'department_id': [1, 2, 1, 2, 3] })  e un DataFrame di dipartimenti: departments_df = pd.DataFrame({ 'department_id': [1, 2, 3], 'department_name': ['HR', 'IT', 'Finance'], 'location': ['New York', 'San Francisco', 'Chicago'] }).
Unire questi DataFrame in base alla colonna comune department_id, in modo da avere nel risultato informazioni sia sui dipendenti che sui dipartimenti, usando la funzione .merge() • Per ogni DataFrame, trasformare la colonna department_id nell'indice, facendo in modo che la modifica sia permanente; poi unire i due dataset mediante il metodo .join() • Ci sono differenze nel risultato? Quali? Perché?

In [47]:
employees_df = pd.DataFrame ({
    'employee_id' : [101, 102, 103, 104, 105],
    'name' : ['Alice', 'Bob', 'Charlie', 'David', 'Emma'],
    'department_id' : [1, 2, 1, 2, 3]
})

departments_df = pd.DataFrame({
    'department_id' : [1, 2, 3],
    'department_name' : ['HR', 'IT', 'Finance'],
    'location' : ['New York', 'San Francisco', 'Chicago']
})

print("EMPLOYEES:")
print(employees_df)
print("\nDEPARTMENTS:")
print(departments_df)

EMPLOYEES:
   employee_id     name  department_id
0          101    Alice              1
1          102      Bob              2
2          103  Charlie              1
3          104    David              2
4          105     Emma              3

DEPARTMENTS:
   department_id department_name       location
0              1              HR       New York
1              2              IT  San Francisco
2              3         Finance        Chicago

In [51]:
# 1. Unisco i due df tramite una funzione .merge()
merged_df = pd.merge(employees_df, departments_df, on = "department_id", how = "inner")
merged_df

   employee_id     name  department_id department_name       location
0          101    Alice              1              HR       New York
1          102      Bob              2              IT  San Francisco
2          103  Charlie              1              HR       New York
3          104    David              2              IT  San Francisco
4          105     Emma              3         Finance        Chicago

In [53]:
#Setto per entrambi i df 'department_id' come indice, poi unisco i due dataset mediante il metodo .join()
employees_department_id = employees_df.set_index('department_id')
departments_department_id = departments_df.set_index('department_id')

joined_df = employees_department_id.join(departments_department_id, how = 'inner')
joined_df

               employee_id     name department_name       location
department_id
1                      101    Alice              HR       New York
2                      102      Bob              IT  San Francisco
1                      103  Charlie              HR       New York
2                      104    David              IT  San Francisco
3                      105     Emma         Finance        Chicago

In [54]:
#Ci sono differenze nel risultato? Quali? Perché?
print('Si, la prima è department_id nella join è diventata un indice, mentre nella merge è una colonna.\n Per il resto è tutto invariato')

Si, la prima è department_id nella join è diventata un indice, mentre nella merge è una colonna.
 Per il resto è tutto invariato

Esercizio 6: • Dal database AdventureWorksDW importiamo le tabelle dimemployee e dimemployeesalesterritory come DataFrame • Effettuiamo un join tra i due DataFrame usando le colonne EmployeeKey • Controlliamo la dimensione del DataFrame risultante: è quella attesa? • Importiamo ora la tabella dimsalesterritory ed effettuiamo un join tra questa e il DataFrame risultante della join precedente, usando le colonne SalesTerritoryKey • Su questo DataFrame contare quanti dipendenti ci sono per ogni paese (country) e per ogni regione (region) • Valutiamo la media del BaseRate per ogni paese: ci sono differenze?

In [55]:
import os
import dotenv
import sqlalchemy
import pandas as pd

dotenv.load_dotenv(dotenv_path="cred.env", override=True)

username = os.getenv("username") 
password = os.getenv("password") 
host = os.getenv("host") 
dbname = os.getenv("dbname") 

connection_string = "mysql+pymysql://"+username+":"+password+"@"+host+"/"+dbname 

db_engine = sqlalchemy.create_engine(connection_string)

In [59]:
# 1. Importo la prima tabella
dimemployee = pd.read_sql("SELECT * FROM dimemployee", db_engine)
dimemployee.sample(10)

,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,LastName,MiddleName,NameStyle,Title,HireDate,...,Gender,PayFrequency,BaseRate,VacationHours,SickLeaveHours,CurrentFlag,SalesPersonFlag,DepartmentName,EmployeePhoto,Position
142,143,112.0,184188301,295847284.0,Laura,Norman,F,0,Chief Financial Officer,2008-08-31,...,F,2,60.0962,0,20,1,0,Executive,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
10,11,3.0,695256908,509647174.0,Gail,Erickson,A,0,Design Engineer,2007-08-06,...,F,2,32.6923,5,22,1,0,Engineering,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
211,212,20.0,63179277,494170342.0,Jay,Adams,G,0,Production Technician - WC60,2008-10-03,...,M,1,12.4500,32,36,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
135,136,177.0,363996959,578935259.0,Michiko,Osada,F,0,Production Technician - WC30,2008-08-26,...,M,1,9.5000,44,42,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
93,94,147.0,212801092,319472946.0,Fadi,Fakhouri,K,0,Production Technician - WC20,2008-08-04,...,M,1,14.0000,16,28,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
256,257,43.0,343861179,885055826.0,Sootha,Charncherngkha,T,0,Quality Assurance Technician,2009-09-23,...,M,2,10.5769,85,62,1,0,Quality Assurance,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
129,130,92.0,242381745,345106466.0,Sean,Chai,N,0,Document Control Assistant,2008-08-22,...,M,2,10.2500,78,59,1,0,Document Control,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
262,263,51.0,28414965,553069203.0,Stuart,Macrae,J,0,Janitor,2009-10-03,...,M,1,9.2500,88,64,1,0,Facilities and Maintenance,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
101,102,89.0,830150469,750905084.0,Michael,Rothkugel,L,0,Production Technician - WC40,2008-08-10,...,M,1,15.0000,70,55,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None
145,146,138.0,764853868,386315192.0,Andy,Ruth,M,0,Production Technician - WC30,2008-08-31,...,M,1,9.5000,39,39,1,0,Production,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,None

In [58]:
# 2. Importo la seconda tabella
dimemployeesalesterritory = pd.read_sql("SELECT * FROM dimemployeesalesterritory", db_engine)
dimemployeesalesterritory.sample(10)

    EmployeeKey  SalesTerritoryKey
4           293                  1
34          294                  9
9           277                  3
27          290                  7
24          284                  6
30          277                  8
17          287                  4
26          277                  7
6           277                  2
18          272                  5

In [60]:
# 3. Effettuo un join tra i due DataFrame usando le colonne EmployeeKey  
first_merge = dimemployee.merge(dimemployeesalesterritory, on='EmployeeKey', how = 'inner')
print(first_merge.shape)

print('\nSi, il risultato è quello atteso.')

(39, 29)

Si, il risultato è quello atteso.

In [61]:
# 4. Importo ora la tabella dimsalesterritory 
dimsalesterritory = pd.read_sql('SELECT * FROM dimsalesterritory', db_engine)
dimsalesterritory

,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup,SalesTerritoryImage
0,1,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
1,2,2,Northeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
2,3,3,Central,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
3,4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
4,5,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
5,6,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
6,7,7,France,France,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
7,8,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
8,9,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
9,10,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
10,11,0,Corporate HQ,Corporate HQ,Corporate HQ,None

In [64]:
# 5. Effettuo un join tra dimsalesterritory e first_merge, usando le colonne SalesTerritoryKey
final_result = first_merge.merge(dimsalesterritory, on = 'SalesTerritoryKey', how = 'inner')
final_result.sample(10)

,EmployeeKey,ParentEmployeeKey,EmployeeNationalIDAlternateKey,ParentEmployeeNationalIDAlternateKey,FirstName,LastName,MiddleName,NameStyle,Title,HireDate,...,SalesPersonFlag,DepartmentName,EmployeePhoto,Position,SalesTerritoryKey,SalesTerritoryAlternateKey,SalesTerritoryRegion,SalesTerritoryCountry,SalesTerritoryGroup,SalesTerritoryImage
38,296,294.0,758596752,481044938.0,Lynn,Tsoflias,N,0,Sales Representative,2012-12-28,...,1,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative,9,9,Australia,Australia,Pacific,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
33,291,290.0,668991357,982310417.0,Jae,Pak,B,0,Sales Representative,2011-12-29,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,10,10,United Kingdom,United Kingdom,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
18,281,272.0,841560125,502097814.0,Michael,Blythe,G,0,Sales Representative,2010-12-29,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,5,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
4,272,277.0,502097814,112432117.0,Stephen,Jiang,Y,0,North American Sales Manager,2010-08-04,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager,5,5,Southeast,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
27,288,272.0,399771412,502097814.0,José,Saraiva,Edvaldo,0,Sales Representative,2010-12-29,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,6,6,Canada,Canada,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
26,287,272.0,139397894,502097814.0,Shu,Ito,K,0,Sales Representative,2010-12-29,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
25,286,272.0,61161660,502097814.0,Pamela,Ansman-Wolfe,O,0,Sales Representative,2010-12-29,...,1,Sales,b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\...,Sales Representative,4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
20,282,272.0,191644724,502097814.0,Linda,Mitchell,C,0,Sales Representative,2010-12-29,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,4,4,Southwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
30,290,277.0,982310417,112432117.0,Amy,Alberts,E,0,European Sales Manager,2011-11-15,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Manager,8,8,Germany,Germany,Europe,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...
35,293,272.0,90836195,502097814.0,Tete,Mensa-Annan,A,0,Sales Representative,2012-04-30,...,1,Sales,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...,Sales Representative,1,1,Northwest,United States,North America,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x01...

In [66]:
# 6. Conto quanti dipendenti ci sono per ogni paese (country) e per ogni regione (region)
final_result.groupby(['SalesTerritoryCountry', 'SalesTerritoryRegion'])['EmployeeKey'].count()

SalesTerritoryCountry  SalesTerritoryRegion
Australia              Australia               3
Canada                 Canada                  4
France                 France                  4
Germany                Germany                 3
United Kingdom         United Kingdom          3
United States          Central                 5
                       Northeast               3
                       Northwest               5
                       Southeast               4
                       Southwest               5
Name: EmployeeKey, dtype: int64

In [67]:
# 7. Valuto la media del BaseRate per ogni paese
final_result.groupby('SalesTerritoryCountry')['BaseRate'].mean().round(2)

SalesTerritoryCountry
Australia         47.76
Canada            41.59
France            41.59
Germany           47.76
United Kingdom    47.76
United States     39.91
Name: BaseRate, dtype: float64